// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Runtime can use a pooled URL; migrations should use a direct URL when
    // the provider exposes both (Neon/Vercel Postgres, Supabase, etc.).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
